// Publishes the pact file(s) generated by `npm test` to the local Pact Broker
// (see ../docker-compose.yml). Run after the consumer tests, before the provider
// verification test in Client.Gateway.Api.Tests.
import { execFileSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const pactsDir = path.resolve(__dirname, '../pacts');
const brokerBaseUrl = process.env.PACT_BROKER_BASE_URL ?? 'http://localhost:9292';
const consumerAppVersion = process.env.PACT_CONSUMER_VERSION ?? gitSha();

// Runs the pact-broker CLI's JS entry point directly through node, rather than
// the node_modules/.bin/pact-broker shim: on Windows that shim is a .cmd file,
// which Node can only spawn via a shell, and a shell means these args would be
// concatenated into a command line unescaped instead of passed as an argv array.
const pactBrokerCli = path.resolve(__dirname, '../node_modules/@pact-foundation/pact-cli/bin/pact-broker.js');

execFileSync(
  process.execPath,
  [
    pactBrokerCli,
    'publish',
    pactsDir,
    `--consumer-app-version=${consumerAppVersion}`,
    '--branch=main',
    `--broker-base-url=${brokerBaseUrl}`,
  ],
  { stdio: 'inherit' },
);

function gitSha() {
  try {
    return execFileSync('git', ['rev-parse', 'HEAD']).toString().trim();
  } catch {
    return '0.0.0-local';
  }
}
